export const BLOCK_TAGS = {
    p: 'paragraph',
    blockquote: 'blockquote',
    hr: 'horizontal-rule',
    pre: 'preformatted',
    ul: 'bulleted-list',
    ol: 'numbered-list',
    li: 'list-item',
    h1: 'heading-one',
    h2: 'heading-two',
    h3: 'heading-three',
    h4: 'heading-four',
    h5: 'heading-five',
    h6: 'heading-six',
    img: 'image',
};
